# Generated by Django 5.1.4 on 2025-09-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('submitted_by', models.CharField(max_length=100)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('ai_judgment', models.TextField(blank=True)),
            ],
        ),
    ]
